---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "tbank"
  namespace: "default"
  labels:
    app: "tbank"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "tbank"
  template:
    metadata:
      labels:
        app: "tbank"
    spec:
      containers:
      - name: "tbank-sha256-1"
        image: "gcr.io/tbank-274715/tbank:latest"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "tbank-hpa-1mqm"
  namespace: "default"
  labels:
    app: "tbank"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "tbank"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "tbank-service"
  namespace: "default"
  labels:
    app: "tbank"
    app.kubernetes.io/managed-by: "graphite-jenkins-gke"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  selector:
    app: "tbank"
  type: "LoadBalancer"
  loadBalancerIP: ""
    