apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:

  selector:
    app: jenkins
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 8000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 2
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000