apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: tbank
  labels:
    name: tbank
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tbank
  template:
    metadata:
      name: tbank
      labels:
        name: tbank
    spec:
      containers:
        - name: tbank
          image: asia.gcr.io/tbank-274715/tbank:v3
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
          env:
            - name: DEBUG_MODE
              value: "1"