apiVersion: apps/v1
kind: Deployment
metadata:
  name: tbank
  labels:
    name: tbank
spec:
  replicas: 2
  selector:
    matchLabels:
      name: tbank
  template:
    metadata:
      name: tbank
      labels:
        name: tbank
    spec:
      containers:
        - name: tbank
          image: asia.gcr.io/tbank-274715/tbank:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
          env:
            - name: DEBUG_MODE
              value: "1"


---
kind: Service
apiVersion: v1
metadata:
  #Service name
  name: tbank
spec:
  selector:
    app: tbank
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
  type: LoadBalancer