---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "tbank"
  namespace: "default"
  labels:
    app: "tbank"
spec:
  replicas: 3
  #strategy:
   # type: RollingUpdate
    #rollingUpdate:
    #  maxSurge: 1
    #  maxUnavailable: 25%
  selector:
    matchLabels:
      app: "tbank"
  template:
    metadata:
      labels:
        app: "tbank"
    spec:
      containers:
      - name: "tbank-sha256-1"
        image: "gcr.io/tbank-274715/tbank@sha256:672275d9b4c7c6d7d39423d9400bdfaaba00e9f5b666fd8b345fa67a06938bcb"
        #readinessProbe:
        #  exec:
        #    command:
        #      - /startup.sh
        #  initialDelaySeconds: 5
         # periodSeconds: 15
         # successThreshold: 1
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "tbank-hpa-1mqm"
  namespace: "default"
  labels:
    app: "tbank"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "tbank"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
