apiVersion: v1
kind: Service
metadata:
  name: tbank
spec:
  selector:
    app: tbank
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tbank
spec:
  selector:
    matchLabels:
      app: tbank
  replicas: 2
  template:
    metadata:
      labels:
        app: tbank
    spec:
      containers:
      - name: tbank
        image: kennykwekjy/jenkins2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000