apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jenkins
  name: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: kennykwekjy/jenkins2:latest
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 8080
status: {}

