apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jenkins2
  name: jenkins2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins2
    spec:
      containers:
      - name: jenkins2
        image: kennykwekjy/jenkins2:latest
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 8080
status: {}

